# Generated by Django 4.2 on 2023-05-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ("-created_at",)},
        ),
    ]
